### ISSUE TITLE
Al css le falta mimo y látigo

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/d-s1-evaluacion-intermedia-SandraCGarcia#4]
Nos amimamos a terminar el ejercicio? o qué?

![Al turrón](https://media.giphy.com/media/AWv3UAFkgz39u/giphy.gif)

**Comment by SandraCGarcia** [comment]
Por supuesto!!

https://giphy.com/gifs/ava-duvernay-blackgirlmagic-black-girl-magic-l41YfdYdptDB9RHIA


Enviado desde mi smartphone Samsung Galaxy.
-------- Mensaje original --------De: Carlos Mañas <notifications@github.com> Fecha: 6/6/18  16:52  (GMT+01:00) Para: Adalab/d-s1-evaluacion-intermedia-SandraCGarcia <d-s1-evaluacion-intermedia-SandraCGarcia@noreply.github.com> Cc: Sandra <sandra.gcanete@gmail.com>, Assign <assign@noreply.github.com> Asunto: [Adalab/d-s1-evaluacion-intermedia-SandraCGarcia] Al css le falta mimo y látigo (#4) 
Nos amimamos a terminar el ejercicio? o qué?


—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/Adalab/d-s1-evaluacion-intermedia-SandraCGarcia/issues/4","url":"https://github.com/Adalab/d-s1-evaluacion-intermedia-SandraCGarcia/issues/4","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Adalab/d-s1-evaluacion-intermedia-SandraCGarcia","title":"Adalab/d-s1-evaluacion-intermedia-SandraCGarcia","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Adalab/d-s1-evaluacion-intermedia-SandraCGarcia"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Al css le falta mimo y látigo (#4)"}],"action":{"name":"View Issue","url":"https://github.com/Adalab/d-s1-evaluacion-intermedia-SandraCGarcia/issues/4"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Al css le falta mimo y látigo (#4)",
"sections": [
{
"text": "",
"activityTitle": "**Carlos Mañas**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@oneeyedman",
"facts": [
{
"name": "Repository: ",
"value": "Adalab/d-s1-evaluacion-intermedia-SandraCGarcia"
},
{
"name": "Issue #: ",
"value": 4
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Adalab/d-s1-evaluacion-intermedia-SandraCGarcia\",\n\"issueId\": 4,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Adalab/d-s1-evaluacion-intermedia-SandraCGarcia\",\n\"issueId\": 4\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Adalab/d-s1-evaluacion-intermedia-SandraCGarcia/issues/4"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 343095092\n}"
}
],
"themeColor": "26292E"
}
